image: openjdk
downloadTermios:
    stage: build
    script:
        - mkdir build
        - curl -L "https://github.com/btj/termios/releases/download/0.7/io.github.btj.termios-0.7.jar" -O
        - javac -cp ./io.github.btj.termios-0.7.jar -d ./build ./src/*/*.java