image: openjdk:21
build:
    stage: build
    script:
        - mkdir build
        - curl -L "https://github.com/btj/termios/releases/download/0.7/io.github.btj.termios-0.7.jar" -O
        - jar xvf ./*.jar
        - cp -vr ./io ./build/
        - javac --version
        - javac -d ./build ./src/*/*.java ./tests/*/*.java

test:
    stage: test
    script:
        - junit-platform-console --class-path ./build/ --scan-classpath ./build/